version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - ${MYSQL_PORT}
    volumes:
      - data_volume:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  data_volume:
